version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  busbooking:
    image: busbooking
    container_name: busbooking-container
    ports:
      - "9090:9090"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb+srv://naveen:12345@cluster0.arybrtd.mongodb.net/bus-db?retryWrites=true&w=majority"
      SERVER_PORT: "9090"
    command: ["java", "-jar", "/app/BusBooking.jar"]
    volumes:
      - ./src/main/resources:/app/resources  # Optional: Mount resources directory if needed
